name: farmer_eats
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_database: ^11.1.4   # Updated to a compatible version
  firebase_storage: ^12.3.4     # Updated to a compatible version
  firebase_auth: ^5.3.0
  random_string: ^2.3.1
  permission_handler: ^11.3.1
  smooth_page_indicator: ^1.2.0
  file_picker: ^5.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/apple_logo.png
    - assets/images/facebook.png
    - assets/images/google_logo.png
    - assets/images/Group.png
    - assets/images/Group 44.png
    - assets/images/Group 46.png
    - assets/images/tick.png
